TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	OrientationConverter.cpp\
	osgconv.cpp\

LIBS     += $(OSG_LIBS) $(GLUT_LIB) $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgconv

INSTFILES =\
	$(CXXFILES)\
	Makefile.inst=Makefile

include $(TOPDIR)/Make/makerules
