TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osggeomdemo.cpp\

LIBS     += -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osggeomdemo


include $(TOPDIR)/Make/makerules
