TOPDIR = ../../..
include $(TOPDIR)/Make/makedefs 

CXXFILES =\
        ReaderWriterJPEG.cpp\

INC += -I/usr/local/include/

LIBS  += $(OSG_LIBS) $(OTHER_LIBS)

PLUGIN = osgdb_jpeg.$(PLUGIN_EXT)

include $(TOPDIR)/Make/makerules 
