TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgcameragroup.cpp\

LIBS     += -losgProducer -lProducer $(OSG_LIBS) $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgcameragroup

INC += $(PRODUCER_INCLUDE_DIR)
LDFLAGS  += $(PRODUCER_LIB_DIR)


include $(TOPDIR)/Make/makerules
