TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osglightpoint.cpp\

LIBS     += -losgSim -losgProducer -lProducer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osglightpoint


INC += $(PRODUCER_INCLUDE_DIR) -I/usr/X11R6/include
LDFLAGS  += $(PRODUCER_LIB_DIR)

include $(TOPDIR)/Make/makerules
