TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgshadow.cpp\

LIBS     += -losgViewer -losgShadow -losgText -losgDB -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgshadow

include $(TOPDIR)/Make/makerules
