// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/BoundingSphere>
#include <osg/CopyOp>
#include <osg/NodeVisitor>
#include <osg/Object>
#include <osgParticle/ParticleSystem>
#include <osgParticle/ParticleSystemUpdater>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgParticle::ParticleSystemUpdater)
	I_BaseType(osg::Node);
	I_Constructor0();
	I_ConstructorWithDefaults2(IN, const osgParticle::ParticleSystemUpdater &, copy, , IN, const osg::CopyOp &, copyop, osg::CopyOp::SHALLOW_COPY);
	I_Method0(osg::Object *, cloneType);
	I_Method1(osg::Object *, clone, IN, const osg::CopyOp &, copyop);
	I_Method1(bool, isSameKindAs, IN, const osg::Object *, obj);
	I_Method0(const char *, className);
	I_Method0(const char *, libraryName);
	I_Method1(void, accept, IN, osg::NodeVisitor &, nv);
	I_Method1(bool, addParticleSystem, IN, osgParticle::ParticleSystem *, ps);
	I_Method1(bool, removeParticleSystem, IN, osgParticle::ParticleSystem *, ps);
	I_MethodWithDefaults2(bool, removeParticleSystem, IN, unsigned int, i, , IN, unsigned int, numParticleSystemsToRemove, 1);
	I_Method2(bool, replaceParticleSystem, IN, osgParticle::ParticleSystem *, origPS, IN, osgParticle::ParticleSystem *, newPS);
	I_Method2(bool, setParticleSystem, IN, unsigned int, i, IN, osgParticle::ParticleSystem *, ps);
	I_Method0(unsigned int, getNumParticleSystems);
	I_Method1(osgParticle::ParticleSystem *, getParticleSystem, IN, unsigned int, i);
	I_Method1(const osgParticle::ParticleSystem *, getParticleSystem, IN, unsigned int, i);
	I_Method1(bool, containsParticleSystem, IN, const osgParticle::ParticleSystem *, ps);
	I_Method1(unsigned int, getParticleSystemIndex, IN, const osgParticle::ParticleSystem *, ps);
	I_Method1(void, traverse, IN, osg::NodeVisitor &, nv);
	I_Method0(osg::BoundingSphere, computeBound);
	I_ArrayProperty_GSA(osgParticle::ParticleSystem *, ParticleSystem, ParticleSystems, unsigned int, bool);
END_REFLECTOR

