// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/CopyOp>
#include <osg/NodeVisitor>
#include <osg/Object>
#include <osgParticle/Program>

BEGIN_ABSTRACT_OBJECT_REFLECTOR(osgParticle::Program)
	BaseType(osgParticle::ParticleProcessor);
	Constructor0();
	ConstructorWithDefaults2(IN, const osgParticle::Program &, copy, , IN, const osg::CopyOp &, copyop, osg::CopyOp::SHALLOW_COPY);
	Method0(const char *, libraryName);
	Method0(const char *, className);
	Method1(bool, isSameKindAs, IN, const osg::Object *, obj);
	Method1(void, accept, IN, osg::NodeVisitor &, nv);
END_REFLECTOR

