TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgshape.cpp\

LIBS     += -losgViewer -losgText -losgDB -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgshape

include $(TOPDIR)/Make/makerules
