TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgmanipulator.cpp\

LIBS     += -losgViewer -losgManipulator -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgmanipulator

INC += $(X_INC)

include $(TOPDIR)/Make/makerules
