#!smake
include ../../../Make/makedefs

C++FILES = \
	ReaderWriterTGZ.cpp\


LIB = ../../../lib/osgPlugins/osgdb_tgz.so

TARGET_LOADER_FILES = osgPlugins/osgdb_tgz.so

C++FLAGS += -I../../../include
LDFLAGS += -L../../../lib

include ../../../Make/makerules



