char shadergen_vert[] = "// ShaderGen shader\n"
                        "// new version\n"
                        "#ifdef GL_ES\n"
                        "    precision highp float;\n"
                        "#endif\n"
                        "\n"
                        "#pragma import_defines(GL_LIGHTING, GL_TEXTURE_2D, GL_FOG)\n"
                        "\n"
                        "#if defined(GL_LIGHTING)\n"
                        "varying vec3 normalDir;\n"
                        "varying vec3 lightDir;\n"
                        "#endif\n"
                        "\n"
                        "#if defined(GL_LIGHTING) || defined(GL_FOG)\n"
                        "varying vec3 viewDir;\n"
                        "#endif\n"
                        "\n"
                        "varying vec4 vertexColor;\n"
                        "\n"
                        "\n"
                        "void main()\n"
                        "{\n"
                        "  gl_Position = ftransform();\n"
                        "\n"
                        "#if defined(GL_TEXTURE_2D)\n"
                        "  gl_TexCoord[0] = gl_MultiTexCoord0;\n"
                        "#endif\n"
                        "\n"
                        "#if defined(GL_LIGHTING) || defined(GL_FOG)\n"
                        "  viewDir = -vec3(gl_ModelViewMatrix * gl_Vertex);\n"
                        "#endif\n"
                        "\n"
                        "#if defined(GL_LIGHTING)\n"
                        "  normalDir = gl_NormalMatrix * gl_Normal;\n"
                        "  vec4 lpos = gl_LightSource[0].position;\n"
                        "  if (lpos.w == 0.0)\n"
                        "    lightDir = lpos.xyz;\n"
                        "  else\n"
                        "    lightDir = lpos.xyz + viewDir;\n"
                        "#endif\n"
                        "\n"
                        "  vertexColor = gl_Color;\n"
                        "}\n"
                        "\n";
