#!smake
include ../../../Make/makedefs

C++FILES = \
        hat.cpp\
        vector.cpp\
        matrix.cpp\
	fly.cpp\
	terrain.cpp\
	tank.cpp\
	sky.cpp\
	base.cpp\
	trees.cpp\


LIB = ../../../lib/osgPlugins/osgdb_fly.so

TARGET_LOADER_FILES = osgPlugins/osgdb_fly.so

C++FLAGS += -I../../../include
LDFLAGS += -L../../../lib

include ../../../Make/makerules



