TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgpbuffer.cpp\

LIBS     += -losgProducer -lProducer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgpbuffer

INC += $(X_INC)

include $(TOPDIR)/Make/makerules
