// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgGA/GUIEventAdapter>

BEGIN_ENUM_REFLECTOR(osgGA::GUIEventAdapter::MouseButtonMask)
	EnumLabel(osgGA::GUIEventAdapter::LEFT_MOUSE_BUTTON);
	EnumLabel(osgGA::GUIEventAdapter::MIDDLE_MOUSE_BUTTON);
	EnumLabel(osgGA::GUIEventAdapter::RIGHT_MOUSE_BUTTON);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osgGA::GUIEventAdapter::EventType)
	EnumLabel(osgGA::GUIEventAdapter::NONE);
	EnumLabel(osgGA::GUIEventAdapter::PUSH);
	EnumLabel(osgGA::GUIEventAdapter::RELEASE);
	EnumLabel(osgGA::GUIEventAdapter::DOUBLECLICK);
	EnumLabel(osgGA::GUIEventAdapter::DRAG);
	EnumLabel(osgGA::GUIEventAdapter::MOVE);
	EnumLabel(osgGA::GUIEventAdapter::KEYDOWN);
	EnumLabel(osgGA::GUIEventAdapter::KEYUP);
	EnumLabel(osgGA::GUIEventAdapter::FRAME);
	EnumLabel(osgGA::GUIEventAdapter::RESIZE);
	EnumLabel(osgGA::GUIEventAdapter::SCROLLUP);
	EnumLabel(osgGA::GUIEventAdapter::SCROLLDOWN);
	EnumLabel(osgGA::GUIEventAdapter::SCROLLLEFT);
	EnumLabel(osgGA::GUIEventAdapter::SCROLLRIGHT);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osgGA::GUIEventAdapter::KeySymbol)
	EnumLabel(osgGA::GUIEventAdapter::KEY_Space);
	EnumLabel(osgGA::GUIEventAdapter::KEY_BackSpace);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Tab);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Linefeed);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Clear);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Return);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Pause);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Scroll_Lock);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Sys_Req);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Escape);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Delete);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Home);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Left);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Up);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Right);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Down);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Prior);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Page_Up);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Next);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Page_Down);
	EnumLabel(osgGA::GUIEventAdapter::KEY_End);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Begin);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Select);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Print);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Execute);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Insert);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Undo);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Redo);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Menu);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Find);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Cancel);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Help);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Break);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Mode_switch);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Script_switch);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Num_Lock);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Space);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Tab);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Enter);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_F1);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_F2);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_F3);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_F4);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Home);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Left);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Up);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Right);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Down);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Prior);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Page_Up);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Next);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Page_Down);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_End);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Begin);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Insert);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Delete);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Equal);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Multiply);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Add);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Separator);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Subtract);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Decimal);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_Divide);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_0);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_1);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_2);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_3);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_4);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_5);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_6);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_7);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_8);
	EnumLabel(osgGA::GUIEventAdapter::KEY_KP_9);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F1);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F2);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F3);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F4);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F5);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F6);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F7);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F8);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F9);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F10);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F11);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F12);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F13);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F14);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F15);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F16);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F17);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F18);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F19);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F20);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F21);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F22);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F23);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F24);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F25);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F26);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F27);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F28);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F29);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F30);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F31);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F32);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F33);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F34);
	EnumLabel(osgGA::GUIEventAdapter::KEY_F35);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Shift_L);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Shift_R);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Control_L);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Control_R);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Caps_Lock);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Shift_Lock);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Meta_L);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Meta_R);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Alt_L);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Alt_R);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Super_L);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Super_R);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Hyper_L);
	EnumLabel(osgGA::GUIEventAdapter::KEY_Hyper_R);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osgGA::GUIEventAdapter::ModKeyMask)
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_LEFT_SHIFT);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_RIGHT_SHIFT);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_LEFT_CTRL);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_RIGHT_CTRL);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_LEFT_ALT);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_RIGHT_ALT);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_LEFT_META);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_RIGHT_META);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_NUM_LOCK);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_CAPS_LOCK);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_CTRL);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_SHIFT);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_ALT);
	EnumLabel(osgGA::GUIEventAdapter::MODKEY_META);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osgGA::GUIEventAdapter::MouseYOrientation)
	EnumLabel(osgGA::GUIEventAdapter::Y_INCREASING_UPWARDS);
	EnumLabel(osgGA::GUIEventAdapter::Y_INCREASING_DOWNWARDS);
END_REFLECTOR

BEGIN_ABSTRACT_OBJECT_REFLECTOR(osgGA::GUIEventAdapter)
	BaseType(osg::Referenced);
	Method0(osgGA::GUIEventAdapter::EventType, getEventType);
	Method0(int, getKey);
	Method0(int, getButton);
	Method1(void, setMouseYOrientation, IN, osgGA::GUIEventAdapter::MouseYOrientation, myo);
	Method0(osgGA::GUIEventAdapter::MouseYOrientation, getMouseYOrientation);
	Method0(float, getXmin);
	Method0(float, getXmax);
	Method0(float, getYmin);
	Method0(float, getYmax);
	Method0(float, getX);
	Method0(float, getY);
	Method0(unsigned int, getButtonMask);
	Method0(unsigned int, getModKeyMask);
	Method0(double, time);
	Method0(float, getXnormalized);
	Method0(float, getYnormalized);
	ReadOnlyProperty(int, Button);
	ReadOnlyProperty(unsigned int, ButtonMask);
	ReadOnlyProperty(osgGA::GUIEventAdapter::EventType, EventType);
	ReadOnlyProperty(int, Key);
	ReadOnlyProperty(unsigned int, ModKeyMask);
	Property(osgGA::GUIEventAdapter::MouseYOrientation, MouseYOrientation);
	ReadOnlyProperty(float, X);
	ReadOnlyProperty(float, Xmax);
	ReadOnlyProperty(float, Xmin);
	ReadOnlyProperty(float, Xnormalized);
	ReadOnlyProperty(float, Y);
	ReadOnlyProperty(float, Ymax);
	ReadOnlyProperty(float, Ymin);
	ReadOnlyProperty(float, Ynormalized);
END_REFLECTOR

