TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
        SlideShowConstructor.cpp\
        SlideEventHandler.cpp\
        DefaultPresentation.cpp\
        ReaderWriterXML.cpp\
	slideshow3D.cpp\

LIBS     += -lxml2 -losgProducer -lProducer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = slideshow3D

INC += $(PRODUCER_INCLUDE_DIR) $(X_INC) $(LIBXML2_INCLUDE)
LDFLAGS  += $(PRODUCER_LIB_DIR)

include $(TOPDIR)/Make/makerules
