// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/NodeVisitor>
#include <osg/State>
#include <osg/StateSet>
#include <osgFX/Effect>
#include <osgFX/Technique>

BEGIN_ABSTRACT_OBJECT_REFLECTOR(osgFX::Technique)
	BaseType(osg::Referenced);
	Constructor0();
	Method0(const char *, techniqueName);
	Method0(const char *, techniqueDescription);
	Method1(void, getRequiredExtensions, IN, std::vector< std::string > &, x);
	Method1(bool, validate, IN, osg::State &, x);
	Method0(int, getNumPasses);
	Method1(osg::StateSet *, getPassStateSet, IN, int, i);
	Method1(const osg::StateSet *, getPassStateSet, IN, int, i);
	Method2(void, traverse, IN, osg::NodeVisitor &, nv, IN, osgFX::Effect *, fx);
END_REFLECTOR

STD_VECTOR_REFLECTOR(std::vector< std::string > &);

