TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgmultitexture.cpp\

LIBS     += -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgmultitexture


include $(TOPDIR)/Make/makerules
