// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/BlendEquation>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ENUM_REFLECTOR(osg::BlendEquation::Equation)
	I_EnumLabel(osg::BlendEquation::RGBA_MIN);
	I_EnumLabel(osg::BlendEquation::RGBA_MAX);
	I_EnumLabel(osg::BlendEquation::ALPHA_MIN);
	I_EnumLabel(osg::BlendEquation::ALPHA_MAX);
	I_EnumLabel(osg::BlendEquation::LOGIC_OP);
	I_EnumLabel(osg::BlendEquation::FUNC_ADD);
	I_EnumLabel(osg::BlendEquation::FUNC_SUBTRACT);
	I_EnumLabel(osg::BlendEquation::FUNC_REVERSE_SUBTRACT);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::BlendEquation::Equation)
	I_EnumLabel(osg::BlendEquation::RGBA_MIN);
	I_EnumLabel(osg::BlendEquation::RGBA_MAX);
	I_EnumLabel(osg::BlendEquation::ALPHA_MIN);
	I_EnumLabel(osg::BlendEquation::ALPHA_MAX);
	I_EnumLabel(osg::BlendEquation::LOGIC_OP);
	I_EnumLabel(osg::BlendEquation::FUNC_ADD);
	I_EnumLabel(osg::BlendEquation::FUNC_SUBTRACT);
	I_EnumLabel(osg::BlendEquation::FUNC_REVERSE_SUBTRACT);
END_REFLECTOR

