// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/ColorMask>
#include <osg/CopyOp>
#include <osg/Object>
#include <osg/State>
#include <osg/StateAttribute>

BEGIN_OBJECT_REFLECTOR(osg::ColorMask)
	BaseType(osg::StateAttribute);
	Constructor0();
	Constructor4(IN, bool, red, IN, bool, green, IN, bool, blue, IN, bool, alpha);
	ConstructorWithDefaults2(IN, const osg::ColorMask &, cm, , IN, const osg::CopyOp &, copyop, osg::CopyOp::SHALLOW_COPY);
	Method0(osg::Object *, cloneType);
	Method1(osg::Object *, clone, IN, const osg::CopyOp &, copyop);
	Method1(bool, isSameKindAs, IN, const osg::Object *, obj);
	Method0(const char *, libraryName);
	Method0(const char *, className);
	Method0(osg::StateAttribute::Type, getType);
	Method1(int, compare, IN, const osg::StateAttribute &, sa);
	Method4(void, setMask, IN, bool, red, IN, bool, green, IN, bool, blue, IN, bool, alpha);
	Method1(void, setRedMask, IN, bool, mask);
	Method0(bool, getRedMask);
	Method1(void, setGreenMask, IN, bool, mask);
	Method0(bool, getGreenMask);
	Method1(void, setBlueMask, IN, bool, mask);
	Method0(bool, getBlueMask);
	Method1(void, setAlphaMask, IN, bool, mask);
	Method0(bool, getAlphaMask);
	Method1(void, apply, IN, osg::State &, state);
	Property(bool, AlphaMask);
	Property(bool, BlueMask);
	Property(bool, GreenMask);
	Property(bool, RedMask);
	ReadOnlyProperty(osg::StateAttribute::Type, Type);
END_REFLECTOR

