// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/DisplaySettings>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::DisplayType)
	I_EnumLabel(osg::DisplaySettings::MONITOR);
	I_EnumLabel(osg::DisplaySettings::POWERWALL);
	I_EnumLabel(osg::DisplaySettings::REALITY_CENTER);
	I_EnumLabel(osg::DisplaySettings::HEAD_MOUNTED_DISPLAY);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::StereoMode)
	I_EnumLabel(osg::DisplaySettings::QUAD_BUFFER);
	I_EnumLabel(osg::DisplaySettings::ANAGLYPHIC);
	I_EnumLabel(osg::DisplaySettings::HORIZONTAL_SPLIT);
	I_EnumLabel(osg::DisplaySettings::VERTICAL_SPLIT);
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE);
	I_EnumLabel(osg::DisplaySettings::RIGHT_EYE);
	I_EnumLabel(osg::DisplaySettings::HORIZONTAL_INTERLACE);
	I_EnumLabel(osg::DisplaySettings::VERTICAL_INTERLACE);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::SplitStereoHorizontalEyeMapping)
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_LEFT_VIEWPORT);
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_RIGHT_VIEWPORT);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::SplitStereoVerticalEyeMapping)
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_TOP_VIEWPORT);
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_BOTTOM_VIEWPORT);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::DisplayType)
	I_EnumLabel(osg::DisplaySettings::MONITOR);
	I_EnumLabel(osg::DisplaySettings::POWERWALL);
	I_EnumLabel(osg::DisplaySettings::REALITY_CENTER);
	I_EnumLabel(osg::DisplaySettings::HEAD_MOUNTED_DISPLAY);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::StereoMode)
	I_EnumLabel(osg::DisplaySettings::QUAD_BUFFER);
	I_EnumLabel(osg::DisplaySettings::ANAGLYPHIC);
	I_EnumLabel(osg::DisplaySettings::HORIZONTAL_SPLIT);
	I_EnumLabel(osg::DisplaySettings::VERTICAL_SPLIT);
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE);
	I_EnumLabel(osg::DisplaySettings::RIGHT_EYE);
	I_EnumLabel(osg::DisplaySettings::HORIZONTAL_INTERLACE);
	I_EnumLabel(osg::DisplaySettings::VERTICAL_INTERLACE);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::SplitStereoHorizontalEyeMapping)
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_LEFT_VIEWPORT);
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_RIGHT_VIEWPORT);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osg::DisplaySettings::SplitStereoVerticalEyeMapping)
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_TOP_VIEWPORT);
	I_EnumLabel(osg::DisplaySettings::LEFT_EYE_BOTTOM_VIEWPORT);
END_REFLECTOR

