// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/CopyOp>
#include <osg/Object>
#include <osg/ShadeModel>
#include <osg/State>
#include <osg/StateAttribute>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ENUM_REFLECTOR(osg::ShadeModel::Mode)
	I_EnumLabel(osg::ShadeModel::FLAT);
	I_EnumLabel(osg::ShadeModel::SMOOTH);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(osg::ShadeModel)
	I_BaseType(osg::StateAttribute);
	I_Constructor0();
	I_ConstructorWithDefaults2(IN, const osg::ShadeModel &, sm, , IN, const osg::CopyOp &, copyop, osg::CopyOp::SHALLOW_COPY);
	I_Method0(osg::Object *, cloneType);
	I_Method1(osg::Object *, clone, IN, const osg::CopyOp &, copyop);
	I_Method1(bool, isSameKindAs, IN, const osg::Object *, obj);
	I_Method0(const char *, libraryName);
	I_Method0(const char *, className);
	I_Method0(osg::StateAttribute::Type, getType);
	I_Method1(int, compare, IN, const osg::StateAttribute &, sa);
	I_Method1(void, setMode, IN, osg::ShadeModel::Mode, mode);
	I_Method0(osg::ShadeModel::Mode, getMode);
	I_Method1(void, apply, IN, osg::State &, state);
	I_Property(osg::ShadeModel::Mode, Mode);
	I_ReadOnlyProperty(osg::StateAttribute::Type, Type);
END_REFLECTOR

