// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/.svn/text-base/Texture2D.svn-base>
#include <osg/State>
#include <osg/Texture2D>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ABSTRACT_OBJECT_REFLECTOR(osg::Texture2D::SubloadCallback)
	I_BaseType(osg::Referenced);
	I_BaseType(osg::Referenced);
	I_Constructor0(____SubloadCallback,
	               "",
	               "");
	I_Method2(void, load, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__load__C5_Texture2D_R1__State_R1,
	          "",
	          "");
	I_Method2(void, subload, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__subload__C5_Texture2D_R1__State_R1,
	          "",
	          "");
	I_Method2(void, load, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__load__C5_Texture2D_R1__State_R1,
	          "",
	          "");
	I_Method2(void, subload, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__subload__C5_Texture2D_R1__State_R1,
	          "",
	          "");
END_REFLECTOR

BEGIN_ABSTRACT_OBJECT_REFLECTOR(osg::Texture2D::SubloadCallback)
	I_BaseType(osg::Referenced);
	I_BaseType(osg::Referenced);
	I_Constructor0(____SubloadCallback,
	               "",
	               "");
	I_Method2(void, load, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__load__C5_Texture2D_R1__State_R1,
	          "",
	          "");
	I_Method2(void, subload, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__subload__C5_Texture2D_R1__State_R1,
	          "",
	          "");
	I_Method2(void, load, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__load__C5_Texture2D_R1__State_R1,
	          "",
	          "");
	I_Method2(void, subload, IN, const osg::Texture2D &, texture, IN, osg::State &, state,
	          Properties::PURE_VIRTUAL,
	          __void__subload__C5_Texture2D_R1__State_R1,
	          "",
	          "");
END_REFLECTOR

