// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/io_utils>

#include <osg/Vec2d>
#include <osg/Vec2f>

TYPE_NAME_ALIAS(double, osg::Vec2d::value_type);

BEGIN_VALUE_REFLECTOR(osg::Vec2d)
	ReaderWriter(osgIntrospection::StdReaderWriter<reflected_type>);	// user-defined
	Comparator(osgIntrospection::PartialOrderComparator<reflected_type>);	// user-defined
	Constructor0();
	Constructor2(IN, osg::Vec2d::value_type, x, IN, osg::Vec2d::value_type, y);
	Constructor1(IN, const osg::Vec2f &, vec);
	Method0(osg::Vec2d::value_type *, ptr);
	Method0(const osg::Vec2d::value_type *, ptr);
	Method2(void, set, IN, osg::Vec2d::value_type, x, IN, osg::Vec2d::value_type, y);
	Method0(osg::Vec2d::value_type &, x);
	Method0(osg::Vec2d::value_type &, y);
	Method0(osg::Vec2d::value_type, x);
	Method0(osg::Vec2d::value_type, y);
	Method0(bool, valid);
	Method0(bool, isNaN);
	Method0(osg::Vec2d::value_type, length);
	Method0(osg::Vec2d::value_type, length2);
	Method0(osg::Vec2d::value_type, normalize);
END_REFLECTOR

