// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/Camera>
#include <osg/Matrix>
#include <osg/Matrixd>
#include <osg/Stats>
#include <osg/View>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ABSTRACT_OBJECT_REFLECTOR(osg::View)
	I_VirtualBaseType(osg::Referenced);
	I_Constructor0(____View,
	               "",
	               "");
	I_Method1(void, setStats, IN, osg::Stats *, stats,
	          Properties::NON_VIRTUAL,
	          __void__setStats__osg_Stats_P1,
	          "Set the Stats object used for collect various frame related timing and scene graph stats. ",
	          "");
	I_Method0(osg::Stats *, getStats,
	          Properties::NON_VIRTUAL,
	          __osg_Stats_P1__getStats,
	          "Get the Stats object. ",
	          "");
	I_Method0(const osg::Stats *, getStats,
	          Properties::NON_VIRTUAL,
	          __C5_osg_Stats_P1__getStats,
	          "Get the const Stats object. ",
	          "");
	I_Method1(void, setCamera, IN, osg::Camera *, camera,
	          Properties::NON_VIRTUAL,
	          __void__setCamera__osg_Camera_P1,
	          "Set the master camera of the view. ",
	          "");
	I_Method0(osg::Camera *, getCamera,
	          Properties::NON_VIRTUAL,
	          __osg_Camera_P1__getCamera,
	          "Get the master camera of the view. ",
	          "");
	I_Method0(const osg::Camera *, getCamera,
	          Properties::NON_VIRTUAL,
	          __C5_osg_Camera_P1__getCamera,
	          "Get the const master camera of the view. ",
	          "");
	I_Method1(bool, addSlave, IN, osg::Camera *, camera,
	          Properties::NON_VIRTUAL,
	          __bool__addSlave__osg_Camera_P1,
	          "",
	          "");
	I_Method3(bool, addSlave, IN, osg::Camera *, camera, IN, const osg::Matrix &, projectionOffset, IN, const osg::Matrix &, viewOffse,
	          Properties::NON_VIRTUAL,
	          __bool__addSlave__osg_Camera_P1__C5_osg_Matrix_R1__C5_osg_Matrix_R1,
	          "",
	          "");
	I_Method1(bool, removeSlave, IN, unsigned int, pos,
	          Properties::NON_VIRTUAL,
	          __bool__removeSlave__unsigned_int,
	          "",
	          "");
	I_Method0(unsigned int, getNumSlaves,
	          Properties::NON_VIRTUAL,
	          __unsigned_int__getNumSlaves,
	          "",
	          "");
	I_Method1(osg::View::Slave &, getSlave, IN, unsigned int, pos,
	          Properties::NON_VIRTUAL,
	          __Slave_R1__getSlave__unsigned_int,
	          "",
	          "");
	I_Method1(const osg::View::Slave &, getSlave, IN, unsigned int, pos,
	          Properties::NON_VIRTUAL,
	          __C5_Slave_R1__getSlave__unsigned_int,
	          "",
	          "");
	I_Method1(osg::View::Slave *, findSlaveForCamera, IN, osg::Camera *, camera,
	          Properties::NON_VIRTUAL,
	          __Slave_P1__findSlaveForCamera__osg_Camera_P1,
	          "",
	          "");
	I_Method0(void, updateSlaves,
	          Properties::NON_VIRTUAL,
	          __void__updateSlaves,
	          "",
	          "");
	I_Method1(void, updateSlave, IN, unsigned int, i,
	          Properties::NON_VIRTUAL,
	          __void__updateSlave__unsigned_int,
	          "",
	          "");
	I_SimpleProperty(osg::Camera *, Camera, 
	                 __osg_Camera_P1__getCamera, 
	                 __void__setCamera__osg_Camera_P1);
	I_ArrayProperty(osg::View::Slave &, Slave, 
	                __Slave_R1__getSlave__unsigned_int, 
	                0, 
	                __unsigned_int__getNumSlaves, 
	                0, 
	                0, 
	                __bool__removeSlave__unsigned_int);
	I_SimpleProperty(osg::Stats *, Stats, 
	                 __osg_Stats_P1__getStats, 
	                 __void__setStats__osg_Stats_P1);
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osg::View::Slave)
	I_Constructor0(____Slave,
	               "",
	               "");
	I_Constructor3(IN, osg::Camera *, camera, IN, const osg::Matrixd &, projectionOffset, IN, const osg::Matrixd &, viewOffset,
	               ____Slave__osg_Camera_P1__C5_osg_Matrixd_R1__C5_osg_Matrixd_R1,
	               "",
	               "");
	I_Constructor1(IN, const osg::View::Slave &, rhs,
	               Properties::NON_EXPLICIT,
	               ____Slave__C5_Slave_R1,
	               "",
	               "");
	I_PublicMemberProperty(osg::ref_ptr< osg::Camera >, _camera);
	I_PublicMemberProperty(osg::Matrixd, _projectionOffset);
	I_PublicMemberProperty(osg::Matrixd, _viewOffset);
END_REFLECTOR

