TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgtexture1D.cpp\

LIBS     += -losgViewer -losgText -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgtexture1D

include $(TOPDIR)/Make/makerules
