TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgtexture1D.cpp\

LIBS     += -losgProducer -lProducer -losgText -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgtexture1D

INC += $(PRODUCER_INCLUDE_DIR) $(X_INC)
LDFLAGS  += $(PRODUCER_LIB_DIR)

include $(TOPDIR)/Make/makerules
