char terrain_displacement_mapping_frag[] = "uniform sampler2D colorTexture1;\n"
                                           "uniform sampler2D colorTexture2;\n"
                                           "uniform sampler2D colorTexture3;\n"
                                           "\n"
                                           "varying vec2 texcoord;\n"
                                           "varying vec4 basecolor;\n"
                                           "\n"
                                           "void main(void)\n"
                                           "{\n"
                                           "    float multiplier = 1.0/3.0;\n"
                                           "    vec4 color = texture2D( colorTexture1, texcoord)*multiplier +\n"
                                           "                 texture2D( colorTexture2, texcoord)*multiplier +\n"
                                           "                 texture2D( colorTexture3, texcoord)*multiplier;\n"
                                           "\n"
                                           "#if 1\n"
                                           "    gl_FragColor = basecolor * color;\n"
                                           "#else\n"
                                           "    gl_FragColor = basecolor;//basecolor * color;\n"
                                           "#endif\n"
                                           "}\n"
                                           "\n";
