// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgDB/Output>
#include <osgDB/ParameterOutput>

BEGIN_VALUE_REFLECTOR(osgDB::ParameterOutput)
	Constructor1(IN, osgDB::Output &, fw);
	Constructor2(IN, osgDB::Output &, fw, IN, int, numItemsPerLine);
	Method0(void, begin);
	Method0(void, newLine);
	Method0(void, end);
END_REFLECTOR

