// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgDB/ReentrantMutex>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(osgDB::ReadWriteMutex)
	I_Constructor0(____ReadWriteMutex,
	               "",
	               "");
	I_Method0(int, readLock,
	          __int__readLock,
	          "",
	          "");
	I_Method0(int, readUnlock,
	          __int__readUnlock,
	          "",
	          "");
	I_Method0(int, writeLock,
	          __int__writeLock,
	          "",
	          "");
	I_Method0(int, writeUnlock,
	          __int__writeUnlock,
	          "",
	          "");
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(osgDB::ReentrantMutex)
	I_Constructor0(____ReentrantMutex,
	               "",
	               "");
	I_Method0(int, lock,
	          __int__lock,
	          "",
	          "");
	I_Method0(int, unlock,
	          __int__unlock,
	          "",
	          "");
	I_Method0(int, trylock,
	          __int__trylock,
	          "",
	          "");
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osgDB::ScopedReadLock)
	I_Constructor1(IN, osgDB::ReadWriteMutex &, mutex,
	               ____ScopedReadLock__ReadWriteMutex_R1,
	               "",
	               "");
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osgDB::ScopedWriteLock)
	I_Constructor1(IN, osgDB::ReadWriteMutex &, mutex,
	               ____ScopedWriteLock__ReadWriteMutex_R1,
	               "",
	               "");
END_REFLECTOR

