// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/Geode>
#include <osg/Node>
#include <osgDB/SharedStateManager>

BEGIN_ENUM_REFLECTOR(osgDB::SharedStateManager::ShareMode)
	EnumLabel(osgDB::SharedStateManager::SHARE_NONE);
	EnumLabel(osgDB::SharedStateManager::SHARE_TEXTURES);
	EnumLabel(osgDB::SharedStateManager::SHARE_STATESETS);
	EnumLabel(osgDB::SharedStateManager::SHARE_ALL);
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osgDB::SharedStateManager)
	BaseType(osg::NodeVisitor);
	Constructor0();
	Method1(void, setShareMode, IN, unsigned int, mode);
	Method0(unsigned int, getShareMode);
	Method0(void, prune);
	MethodWithDefaults2(void, share, IN, osg::Node *, node, , IN, OpenThreads::Mutex *, mt, 0);
	Method1(void, apply, IN, osg::Node &, node);
	Method1(void, apply, IN, osg::Geode &, geode);
	Property(unsigned int, ShareMode);
END_REFLECTOR

