TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgdepthshadow.cpp\

LIBS     += -losgViewer -losgText -losgDB -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgdepthshadow

include $(TOPDIR)/Make/makerules
