TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgunittests.cpp\

LIBS     += $(OSG_LIBS) $(GLUT_LIB) $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgunittests


include $(TOPDIR)/Make/makerules
