TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgprerender.cpp\

LIBS     += -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgprerender

include $(TOPDIR)/Make/makerules
