TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgphotoalbum.cpp\

LIBS     += -losgProducer -lProducer -losgText -losgGA -losgDB -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgphotoalbum

INC += $(PRODUCER_INCLUDE_DIR) $(X_INC)
LDFLAGS  += $(PRODUCER_LIB_DIR)


include $(TOPDIR)/Make/makerules
