char volume_accumulateSamples_lit_tf_frag[] = "#version 110\n"
                                              "\n"
                                              "uniform sampler3D volumeTexture;\n"
                                              "\n"
                                              "uniform sampler1D tfTexture;\n"
                                              "uniform float tfScale;\n"
                                              "uniform float tfOffset;\n"
                                              "uniform float TransparencyValue;\n"
                                              "\n"
                                              "uniform float AlphaFuncValue;\n"
                                              "\n"
                                              "varying vec3 lightDirection;\n"
                                              "\n"
                                              "vec4 accumulateSamples(vec4 fragColor, vec3 ts, vec3 te, vec3 dt, float scale, float cutoff, int num_iterations)\n"
                                              "{\n"
                                              "\n"
                                              "    float normalSampleDistance = length(dt);\n"
                                              "    vec3 deltaX = vec3(normalSampleDistance, 0.0, 0.0);\n"
                                              "    vec3 deltaY = vec3(0.0, normalSampleDistance, 0.0);\n"
                                              "    vec3 deltaZ = vec3(0.0, 0.0, normalSampleDistance);\n"
                                              "    vec3 texcoord = te.xyz;\n"
                                              "\n"
                                              "    // scale = mix(scale, 1.0, 1.0);\n"
                                              "    //scale = mix(scale, 1.0, 0.75);\n"
                                              "\n"
                                              "    // scale = 4.0;\n"
                                              "    if (scale>=1.0)\n"
                                              "    {\n"
                                              "        return vec4(1.0,1.0,1.0,1.0);\n"
                                              "        scale = 1.0;\n"
                                              "    }\n"
                                              "\n"
                                              "    while(num_iterations>0 && fragColor.a<cutoff)\n"
                                              "    {\n"
                                              "        float a = texture3D( volumeTexture, texcoord).a;\n"
                                              "        float v = a * tfScale + tfOffset;\n"
                                              "        vec4 color = texture1D( tfTexture, v);\n"
                                              "\n"
                                              "        if (a>AlphaFuncValue)\n"
                                              "        {\n"
                                              "\n"
                                              "            float px = texture3D( volumeTexture, texcoord + deltaX).a;\n"
                                              "            float py = texture3D( volumeTexture, texcoord + deltaY).a;\n"
                                              "            float pz = texture3D( volumeTexture, texcoord + deltaZ).a;\n"
                                              "\n"
                                              "            float nx = texture3D( volumeTexture, texcoord - deltaX).a;\n"
                                              "            float ny = texture3D( volumeTexture, texcoord - deltaY).a;\n"
                                              "            float nz = texture3D( volumeTexture, texcoord - deltaZ).a;\n"
                                              "\n"
                                              "            vec3 grad = vec3(px-nx, py-ny, pz-nz);\n"
                                              "            if (grad.x!=0.0 || grad.y!=0.0 || grad.z!=0.0)\n"
                                              "            {\n"
                                              "                vec3 normal = normalize(grad);\n"
                                              "                float lightScale = 0.1 +  max(0.0, dot(normal.xyz, lightDirection))*0.9;\n"
                                              "\n"
                                              "                color.r *= lightScale;\n"
                                              "                color.g *= lightScale;\n"
                                              "                color.b *= lightScale;\n"
                                              "            }\n"
                                              "\n"
                                              "#if 0\n"
                                              "            float r = color.a * (1.0-fragColor.a)*scale;\n"
                                              "            fragColor.rgb += color.rgb*r;\n"
                                              "            fragColor.a += r;\n"
                                              "#else\n"
                                              "            if (color.a<fragColor.a)\n"
                                              "            {\n"
                                              "                float r = (1.0-fragColor.a)*scale;\n"
                                              "                fragColor.rgb += color.rgb*r;\n"
                                              "                fragColor.a += color.a * r;\n"
                                              "            }\n"
                                              "            else\n"
                                              "            {\n"
                                              "                fragColor = color;\n"
                                              "            }\n"
                                              "#endif\n"
                                              "        }\n"
                                              "\n"
                                              "        texcoord += dt;\n"
                                              "\n"
                                              "        --num_iterations;\n"
                                              "    }\n"
                                              "\n"
                                              "    if (num_iterations>0) fragColor.a = 1.0;\n"
                                              "    if (fragColor.w<AlphaFuncValue) fragColor.w = 0.0;\n"
                                              "\n"
                                              "    return fragColor;\n"
                                              "}\n"
                                              "\n";
