char volume_vert[] = "#version 110\n"
                     "varying vec4 cameraPos;\n"
                     "varying vec4 vertexPos;\n"
                     "varying mat4 texgen;\n"
                     "\n"
                     "void main(void)\n"
                     "{\n"
                     "        gl_Position = ftransform();\n"
                     "\n"
                     "        cameraPos = gl_ModelViewMatrixInverse*vec4(0,0,0,1);\n"
                     "        vertexPos = gl_Vertex;\n"
                     "\n"
                     "        texgen = mat4(gl_ObjectPlaneS[0], \n"
                     "                      gl_ObjectPlaneT[0],\n"
                     "                      gl_ObjectPlaneR[0],\n"
                     "                      gl_ObjectPlaneQ[0]);\n"
                     "}\n";
