TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	GL2Scene.cpp \
	osgshaders.cpp

LIBS     += -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgshaders

include $(TOPDIR)/Make/makerules
