TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	GL2Scene.cpp \
	osgshaders.cpp

LIBS     += -losgProducer -lProducer -losgDB -losgText -losgGL2 -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgshaders

INC += $(PRODUCER_INCLUDE_DIR) -I/usr/X11R6/include
LDFLAGS  += $(PRODUCER_LIB_DIR)

include $(TOPDIR)/Make/makerules
