// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgAnimation/Action>
#include <osgAnimation/ActionVisitor>
#include <osgAnimation/FrameAction>
#include <osgAnimation/Timeline>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgAnimation::ActionVisitor)
	I_DeclaringFile("osgAnimation/ActionVisitor");
	I_BaseType(osg::Referenced);
	I_Method0(const char *, libraryName,
	          Properties::VIRTUAL,
	          __C5_char_P1__libraryName,
	          "",
	          "");
	I_Method0(const char *, className,
	          Properties::VIRTUAL,
	          __C5_char_P1__className,
	          "",
	          "");
	I_Constructor0(____ActionVisitor,
	               "",
	               "");
	I_Method1(void, traverse, IN, osgAnimation::Action &, visitor,
	          Properties::NON_VIRTUAL,
	          __void__traverse__Action_R1,
	          "",
	          "");
	I_Method1(void, pushFrameActionOnStack, IN, const osgAnimation::FrameAction &, fa,
	          Properties::NON_VIRTUAL,
	          __void__pushFrameActionOnStack__C5_FrameAction_R1,
	          "",
	          "");
	I_Method0(void, popFrameAction,
	          Properties::NON_VIRTUAL,
	          __void__popFrameAction,
	          "",
	          "");
	I_Method1(void, pushTimelineOnStack, IN, osgAnimation::Timeline *, tm,
	          Properties::NON_VIRTUAL,
	          __void__pushTimelineOnStack__Timeline_P1,
	          "",
	          "");
	I_Method0(void, popTimeline,
	          Properties::NON_VIRTUAL,
	          __void__popTimeline,
	          "",
	          "");
	I_Method0(osgAnimation::Timeline *, getCurrentTimeline,
	          Properties::NON_VIRTUAL,
	          __Timeline_P1__getCurrentTimeline,
	          "",
	          "");
	I_Method1(void, setCurrentLayer, IN, int, layer,
	          Properties::NON_VIRTUAL,
	          __void__setCurrentLayer__int,
	          "",
	          "");
	I_Method0(int, getCurrentLayer,
	          Properties::NON_VIRTUAL,
	          __int__getCurrentLayer,
	          "",
	          "");
	I_Method0(const std::vector< osgAnimation::FrameAction > &, getStackedFrameAction,
	          Properties::NON_VIRTUAL,
	          __C5_std_vectorT1_FrameAction__R1__getStackedFrameAction,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::Action &, action,
	          Properties::VIRTUAL,
	          __void__apply__Action_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::Timeline &, tm,
	          Properties::VIRTUAL,
	          __void__apply__Timeline_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::BlendIn &, action,
	          Properties::VIRTUAL,
	          __void__apply__BlendIn_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::BlendOut &, action,
	          Properties::VIRTUAL,
	          __void__apply__BlendOut_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::ActionAnimation &, action,
	          Properties::VIRTUAL,
	          __void__apply__ActionAnimation_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::StripAnimation &, action,
	          Properties::VIRTUAL,
	          __void__apply__StripAnimation_R1,
	          "",
	          "");
	I_SimpleProperty(int, CurrentLayer, 
	                 __int__getCurrentLayer, 
	                 __void__setCurrentLayer__int);
	I_SimpleProperty(osgAnimation::Timeline *, CurrentTimeline, 
	                 __Timeline_P1__getCurrentTimeline, 
	                 0);
	I_SimpleProperty(const std::vector< osgAnimation::FrameAction > &, StackedFrameAction, 
	                 __C5_std_vectorT1_FrameAction__R1__getStackedFrameAction, 
	                 0);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osgAnimation::ClearActionVisitor::ClearType)
	I_DeclaringFile("osgAnimation/ActionVisitor");
	I_EnumLabel(osgAnimation::ClearActionVisitor::BEFORE_FRAME);
	I_EnumLabel(osgAnimation::ClearActionVisitor::AFTER_FRAME);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(osgAnimation::ClearActionVisitor)
	I_DeclaringFile("osgAnimation/ActionVisitor");
	I_BaseType(osgAnimation::ActionVisitor);
	I_Method0(const char *, libraryName,
	          Properties::VIRTUAL,
	          __C5_char_P1__libraryName,
	          "",
	          "");
	I_Method0(const char *, className,
	          Properties::VIRTUAL,
	          __C5_char_P1__className,
	          "",
	          "");
	I_ConstructorWithDefaults1(IN, osgAnimation::ClearActionVisitor::ClearType, type, osgAnimation::ClearActionVisitor::BEFORE_FRAME,
	                           Properties::NON_EXPLICIT,
	                           ____ClearActionVisitor__ClearType,
	                           "",
	                           "");
	I_Method1(void, setFrame, IN, unsigned int, frame,
	          Properties::NON_VIRTUAL,
	          __void__setFrame__unsigned_int,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::Timeline &, action,
	          Properties::VIRTUAL,
	          __void__apply__Timeline_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::Action &, action,
	          Properties::VIRTUAL,
	          __void__apply__Action_R1,
	          "",
	          "");
	I_SimpleProperty(unsigned int, Frame, 
	                 0, 
	                 __void__setFrame__unsigned_int);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(osgAnimation::UpdateActionVisitor)
	I_DeclaringFile("osgAnimation/ActionVisitor");
	I_BaseType(osgAnimation::ActionVisitor);
	I_Method0(const char *, libraryName,
	          Properties::VIRTUAL,
	          __C5_char_P1__libraryName,
	          "",
	          "");
	I_Method0(const char *, className,
	          Properties::VIRTUAL,
	          __C5_char_P1__className,
	          "",
	          "");
	I_Constructor0(____UpdateActionVisitor,
	               "",
	               "");
	I_Method1(void, setFrame, IN, unsigned int, frame,
	          Properties::NON_VIRTUAL,
	          __void__setFrame__unsigned_int,
	          "",
	          "");
	I_Method1(bool, isActive, IN, osgAnimation::Action &, action,
	          Properties::NON_VIRTUAL,
	          __bool__isActive__Action_R1,
	          "",
	          "");
	I_Method0(unsigned int, getLocalFrame,
	          Properties::NON_VIRTUAL,
	          __unsigned_int__getLocalFrame,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::Timeline &, action,
	          Properties::VIRTUAL,
	          __void__apply__Timeline_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::Action &, action,
	          Properties::VIRTUAL,
	          __void__apply__Action_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::BlendIn &, action,
	          Properties::VIRTUAL,
	          __void__apply__BlendIn_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::BlendOut &, action,
	          Properties::VIRTUAL,
	          __void__apply__BlendOut_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::ActionAnimation &, action,
	          Properties::VIRTUAL,
	          __void__apply__ActionAnimation_R1,
	          "",
	          "");
	I_Method1(void, apply, IN, osgAnimation::StripAnimation &, action,
	          Properties::VIRTUAL,
	          __void__apply__StripAnimation_R1,
	          "",
	          "");
	I_SimpleProperty(unsigned int, Frame, 
	                 0, 
	                 __void__setFrame__unsigned_int);
	I_SimpleProperty(unsigned int, LocalFrame, 
	                 __unsigned_int__getLocalFrame, 
	                 0);
END_REFLECTOR

STD_VECTOR_REFLECTOR(std::vector< osgAnimation::FrameAction >)

