TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgsimpleviewerSDL.cpp\

LIBS  += -losgViewer -losgText -losgGA -losgDB -losgUtil -losg `sdl-config --libs`  $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgsimpleviewerSDL

INC += $(X_INC) `sdl-config --cflags`

include $(TOPDIR)/Make/makerules
