TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgsimpleviewerGLUT.cpp\

LIBS     += -losgViewer -losgGA -losgDB -losgUtil -losg -lglut $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgsimpleviewerGLUT

INC += $(X_INC)
LDFLAGS  += 

include $(TOPDIR)/Make/makerules
