TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgstereoimage.cpp\

LIBS     += -losgViewer -losgText -losgGA -losgDB -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgstereoimage


include $(TOPDIR)/Make/makerules
