TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgcallback.cpp\

LIBS     += -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgcallback

include $(TOPDIR)/Make/makerules
