TOPDIR = ../../..
include $(TOPDIR)/Make/makedefs 

CXXFILES =\
	broadcaster.cpp\
	osgcluster.cpp\
	receiver.cpp\

LIBS     += $(OSG_LIBS) $(GLUT_LIB) $(GL_LIBS) $(X_LIBS) $(SOCKET_LIBS) $(OTHER_LIBS) 

EXEC = osgcluster

include $(TOPDIR)/Make/makerules 
