TOPDIR = ../../..
include $(TOPDIR)/Make/makedefs 

CXXFILES =\
        ConvertFromPerformer.cpp\
        ConvertToPerformer.cpp\
        ReaderWriterPFB.cpp\

LIBS   += $(OSG_LIBS) $(OTHER_LIBS)

PLUGIN = osgdb_pfb.$(PLUGIN_EXT)

include $(TOPDIR)/Make/makerules 
