TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgdepthpartition.cpp\
	DepthPartitionNode.cpp\
	DistanceAccumulator.cpp\

LIBS     += -losgProducer -lProducer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgdepthpartion

INC += $(X_INC)

include $(TOPDIR)/Make/makerules
