// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/CopyOp>
#include <osg/NodeVisitor>
#include <osg/Object>
#include <osg/Vec3>
#include <osgSim/ScalarBar>
#include <osgSim/ScalarsToColors>

BEGIN_ENUM_REFLECTOR(osgSim::ScalarBar::Orientation)
	EnumLabel(osgSim::ScalarBar::HORIZONTAL);
	EnumLabel(osgSim::ScalarBar::VERTICAL);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(osgSim::ScalarBar)
	BaseType(osg::Geode);
	Constructor0();
	ConstructorWithDefaults7(IN, int, numColors, , IN, int, numLabels, , IN, osgSim::ScalarsToColors *, stc, , IN, const std::string &, title, , IN, osgSim::ScalarBar::Orientation, orientation, osgSim::ScalarBar::HORIZONTAL, IN, float, aspectRatio, 0.25, IN, osgSim::ScalarBar::ScalarPrinter *, sp, new osgSim::ScalarBar::ScalarPrinter);
	Constructor2(IN, const osgSim::ScalarBar &, rhs, IN, const osg::CopyOp &, co);
	Method0(osg::Object *, cloneType);
	Method1(osg::Object *, clone, IN, const osg::CopyOp &, copyop);
	Method1(bool, isSameKindAs, IN, const osg::Object *, obj);
	Method0(const char *, className);
	Method0(const char *, libraryName);
	Method1(void, accept, IN, osg::NodeVisitor &, nv);
	Method1(void, setNumColors, IN, int, numColors);
	Method0(int, getNumColors);
	Method1(void, setNumLabels, IN, int, numLabels);
	Method0(int, getNumLabels);
	Method1(void, setScalarsToColors, IN, osgSim::ScalarsToColors *, stc);
	Method0(const osgSim::ScalarsToColors *, getScalarsToColors);
	Method1(void, setTitle, IN, const std::string &, title);
	Method0(std::string, getTitle);
	Method1(void, setPosition, IN, const osg::Vec3 &, pos);
	Method0(const osg::Vec3 &, getPosition);
	Method1(void, setWidth, IN, float, width);
	Method0(float, getWidth);
	Method1(void, setAspectRatio, IN, float, aspectRatio);
	Method0(float, getAspectRatio);
	Method1(void, setOrientation, IN, osgSim::ScalarBar::Orientation, orientation);
	Method0(osgSim::ScalarBar::Orientation, getOrientation);
	Method1(void, setScalarPrinter, IN, osgSim::ScalarBar::ScalarPrinter *, sp);
	Method0(const osgSim::ScalarBar::ScalarPrinter *, getScalarPrinter);
	Method1(void, setTextProperties, IN, const osgSim::ScalarBar::TextProperties &, tp);
	Method0(const osgSim::ScalarBar::TextProperties &, getTextProperties);
	Method0(void, update);
	Property(float, AspectRatio);
	WriteOnlyProperty(int, NumColors);
	WriteOnlyProperty(int, NumLabels);
	Property(osgSim::ScalarBar::Orientation, Orientation);
	Property(const osg::Vec3 &, Position);
	WriteOnlyProperty(osgSim::ScalarBar::ScalarPrinter *, ScalarPrinter);
	WriteOnlyProperty(osgSim::ScalarsToColors *, ScalarsToColors);
	Property(const osgSim::ScalarBar::TextProperties &, TextProperties);
	ReadOnlyProperty(std::string, Title);
	Property(float, Width);
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osgSim::ScalarBar::ScalarPrinter)
	BaseType(osg::Referenced);
	Constructor0();
	Method1(std::string, printScalar, IN, float, scalar);
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osgSim::ScalarBar::TextProperties)
	Constructor0();
END_REFLECTOR

