TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgcamera.cpp\

LIBS     += -losgViewer -losgText -losgDB --losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgcamera

include $(TOPDIR)/Make/makerules
