TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgsimple.cpp\

LIBS     += -losgViewer -losgDB --losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgsimple

include $(TOPDIR)/Make/makerules
