TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgbillboard.cpp

LIBS     += -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgbillboard

include $(TOPDIR)/Make/makerules
