TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgbillboard.cpp

LIBS     += -losgProducer -lProducer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 


EXEC = osgbillboard

INC += $(PRODUCER_INCLUDE_DIR) $(X_INC)
LDFLAGS  += $(PRODUCER_LIB_DIR)

include $(TOPDIR)/Make/makerules
