TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgimpostor.cpp\

LIBS     += -losgViewer -losgSim -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgimpostor

include $(TOPDIR)/Make/makerules
