TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	base.cpp\
	GliderManipulator.cpp\
	hangglide.cpp\
	hat.cpp\
	ReaderWriterFLY.cpp\
	sky.cpp\
	tank.cpp\
	terrain.cpp\
	trees.cpp\

LIBS     += $(OSG_LIBS) $(GLUT_LIB) $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osghangglide

include $(TOPDIR)/Make/makerules
