TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgautotransform.cpp\

LIBS     += -losgViewer -losgText -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgautotransform

include $(TOPDIR)/Make/makerules
