TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgforest.cpp\

LIBS     += -losgViewer -losgText -losgDB -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS) 

EXEC = osgforest

include $(TOPDIR)/Make/makerules
