TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	OrientationConverter.cpp\
	osgconv.cpp\

LIBS     += -losg -losgUtil -losgDB  $(GL_LIBS) $(OTHER_LIBS) 

EXEC = osgconv

INSTFILES =\
	$(CXXFILES)\
	Makefile.inst=Makefile

INC += $(PRODUCER_INCLUDE_DIR)
LDFLAGS  += $(PRODUCER_LIB_DIR)

include $(TOPDIR)/Make/makerules
