TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	osgscalarbar.cpp\

LIBS     += -losgText -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(OTHER_LIBS)

EXEC = osgscalarbar

INC += $(X_INC)

include $(TOPDIR)/Make/makerules
