#!smake
include ../../../Make/makedefs

C++FILES = \
	osgtgz.cpp\


LIB = ../../../lib/osgPlugins/osgdb_osgtgz.so

TARGET_LOADER_FILES = osgPlugins/osgdb_osgtgz.so

C++FLAGS += -I../../../include
LDFLAGS += -L../../../lib

include ../../../Make/makerules



