// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/CopyOp>
#include <osg/Node>
#include <osg/NodeVisitor>
#include <osg/Object>
#include <osgAnimation/Channel>
#include <osgAnimation/StackedTransform>
#include <osgAnimation/UpdateMatrixTransform>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgAnimation::UpdateMatrixTransform)
	I_DeclaringFile("osgAnimation/UpdateMatrixTransform");
	I_Method0(osg::Object *, cloneType,
	          Properties::VIRTUAL,
	          __osg_Object_P1__cloneType,
	          "Clone the type of an object, with Object* return type. ",
	          "Must be defined by derived classes. ");
	I_Method1(osg::Object *, clone, IN, const osg::CopyOp &, x,
	          Properties::VIRTUAL,
	          __osg_Object_P1__clone__C5_osg_CopyOp_R1,
	          "Clone an object, with Object* return type. ",
	          "Must be defined by derived classes. ");
	I_Method1(bool, isSameKindAs, IN, const osg::Object *, obj,
	          Properties::VIRTUAL,
	          __bool__isSameKindAs__C5_osg_Object_P1,
	          "",
	          "");
	I_Method0(const char *, libraryName,
	          Properties::VIRTUAL,
	          __C5_char_P1__libraryName,
	          "return the name of the object's library. ",
	          "Must be defined by derived classes. The OpenSceneGraph convention is that the namespace of a library is the same as the library name. ");
	I_Method0(const char *, className,
	          Properties::VIRTUAL,
	          __C5_char_P1__className,
	          "return the name of the object's class type. ",
	          "Must be defined by derived classes. ");
	I_ConstructorWithDefaults1(IN, const std::string &, name, "",
	                           Properties::NON_EXPLICIT,
	                           ____UpdateMatrixTransform__C5_std_string_R1,
	                           "",
	                           "");
	I_ConstructorWithDefaults2(IN, const osgAnimation::UpdateMatrixTransform &, apc, , IN, const osg::CopyOp &, copyop, osg::CopyOp::SHALLOW_COPY,
	                           ____UpdateMatrixTransform__C5_UpdateMatrixTransform_R1__C5_osg_CopyOp_R1,
	                           "",
	                           "");
	I_Method1(bool, link, IN, osgAnimation::Channel *, channel,
	          Properties::VIRTUAL,
	          __bool__link__osgAnimation_Channel_P1,
	          "",
	          "");
	I_Method0(osgAnimation::StackedTransform &, getStackedTransforms,
	          Properties::NON_VIRTUAL,
	          __StackedTransform_R1__getStackedTransforms,
	          "",
	          "");
	I_Method0(const osgAnimation::StackedTransform &, getStackedTransforms,
	          Properties::NON_VIRTUAL,
	          __C5_StackedTransform_R1__getStackedTransforms,
	          "",
	          "");
	I_SimpleProperty(osgAnimation::StackedTransform &, StackedTransforms, 
	                 __StackedTransform_R1__getStackedTransforms, 
	                 0);
END_REFLECTOR

