TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	broadcaster.cpp\
	osgcluster.cpp\
	receiver.cpp\

LIBS     += -losgProducer -lProducer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(SOCKET_LIBS) $(OTHER_LIBS) 

EXEC = osgcluster

INC += $(PRODUCER_INCLUDE_DIR) -I/usr/X11R6/include
LDFLAGS += $(PRODUCER_LIB_DIR)

include $(TOPDIR)/Make/makerules
