TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

CXXFILES =\
	broadcaster.cpp\
	osgcluster.cpp\
	receiver.cpp\

LIBS     += -losgViewer -losgDB -losgText -losgUtil -losg $(GL_LIBS) $(X_LIBS) $(SOCKET_LIBS) $(OTHER_LIBS) 

EXEC = osgcluster

include $(TOPDIR)/Make/makerules
