char text_greyscale_frag[] = "$OSG_GLSL_VERSION\n"
                             "$OSG_GLSL_PRECISION_FLOAT\n"
                             "\n"
                             "#pragma import_defines( BACKDROP_COLOR, OUTLINE, ALPHA )\n"
                             "\n"
                             "#if __VERSION__>=130\n"
                             "    #define TEXTURE texture\n"
                             "    out vec4 osg_FragColor;\n"
                             "#else\n"
                             "    #define TEXTURE texture2D\n"
                             "    #define osg_FragColor gl_FragColor\n"
                             "#endif\n"
                             "\n"
                             "uniform sampler2D glyphTexture;\n"
                             "\n"
                             "$OSG_VARYING_IN vec2 texCoord;\n"
                             "$OSG_VARYING_IN vec4 vertexColor;\n"
                             "\n"
                             "#if !defined(GL_ES) && __VERSION__>=130\n"
                             "    #define ALPHA r\n"
                             "#else\n"
                             "    #define ALPHA a\n"
                             "#endif\n"
                             "\n"
                             "void main(void)\n"
                             "{\n"
                             "    float alpha = TEXTURE(glyphTexture, texCoord).ALPHA;\n"
                             "\n"
                             "    if (alpha==0.0) discard;\n"
                             "\n"
                             "    osg_FragColor = vec4(vertexColor.rgb, alpha);\n"
                             "}\n"
                             "\n";
