char text_sdf_frag[] = "$OSG_GLSL_VERSION\n"
                       "$OSG_PRECISION_FLOAT\n"
                       "\n"
                       "#pragma import_defines( BACKDROP_COLOR, OUTLINE )\n"
                       "\n"
                       "#if __VERSION__>=400\n"
                       "    #define osg_TextureQueryLOD textureQueryLod\n"
                       "    #define USE_SIGNED_DISTNACE_FIELD\n"
                       "#else\n"
                       "    #extension GL_ARB_texture_query_lod : enable\n"
                       "    #ifdef GL_ARB_texture_query_lod\n"
                       "        #define osg_TextureQueryLOD textureQueryLOD\n"
                       "        #define USE_SIGNED_DISTNACE_FIELD\n"
                       "    #endif\n"
                       "#endif\n"
                       "\n"
                       "//#undef USE_SIGNED_DISTNACE_FIELD\n"
                       "\n"
                       "#if __VERSION__>=130\n"
                       "    #define TEXTURE texture\n"
                       "    out vec4 osg_FragColor;\n"
                       "#else\n"
                       "    #define TEXTURE texture2D\n"
                       "    #define osg_FragColor gl_FragColor\n"
                       "#endif\n"
                       "\n"
                       "uniform sampler2D glyphTexture;\n"
                       "\n"
                       "$OSG_VARYING_IN vec2 texCoord;\n"
                       "$OSG_VARYING_IN vec4 vertexColor;\n"
                       "\n"
                       "vec4 textureColor()\n"
                       "{\n"
                       "    #ifdef OUTLINE\n"
                       "        // glyph.rgba = (signed_distance, thin_outline, thick_outline, glyph_alpha)\n"
                       "        vec4 glyph = TEXTURE(glyphTexture, texCoord);\n"
                       "\n"
                       "    #if 0\n"
                       "        float blend_ratio = OUTLINE*17.0;\n"
                       "\n"
                       "        float outline_alpha = 0.0;\n"
                       "        if (blend_ratio>2.0) outline_alpha = glyph.b;\n"
                       "        else if (blend_ratio>1.0) outline_alpha = mix(glyph.g, glyph.b, blend_ratio-1.0);\n"
                       "        else outline_alpha = glyph.g*blend_ratio;\n"
                       "    #else\n"
                       "        float outline_alpha = glyph.g;\n"
                       "        //float outline_alpha = glyph.b;\n"
                       "    #endif\n"
                       "\n"
                       "        float alpha = glyph.a+outline_alpha;\n"
                       "        if (alpha>1.0) alpha = 1.0;\n"
                       "\n"
                       "        return vec4( vertexColor.rgb*glyph.a + BACKDROP_COLOR.rgb*outline_alpha, alpha);\n"
                       "\n"
                       "    #else\n"
                       "        float alpha = TEXTURE(glyphTexture, texCoord).a;\n"
                       "        if (alpha==0.0) vec4(0.0, 0.0, 0.0, 0.0);\n"
                       "        return vec4(vertexColor.rgb, alpha);\n"
                       "    #endif\n"
                       "}\n"
                       "\n"
                       "#ifdef USE_SIGNED_DISTNACE_FIELD\n"
                       "vec4 distanceFieldColor()\n"
                       "{\n"
                       "    float center_alpha = TEXTURE(glyphTexture, texCoord).r;\n"
                       "\n"
                       "    float blend_width = 0.2;\n"
                       "    float distance_scale = 5.0;\n"
                       "    float edge_distance = (center_alpha-0.5)*distance_scale;\n"
                       "\n"
                       "    #ifdef OUTLINE\n"
                       "        float outline_width = OUTLINE*17.0;//0.5;\n"
                       "        if (edge_distance>blend_width*0.5)\n"
                       "        {\n"
                       "            return vertexColor;\n"
                       "        }\n"
                       "        else if (edge_distance>-blend_width*0.5)\n"
                       "        {\n"
                       "            return mix(vertexColor, BACKDROP_COLOR, (blend_width*0.5-edge_distance)/(blend_width));\n"
                       "        }\n"
                       "        else if (edge_distance>(blend_width-outline_width))\n"
                       "        {\n"
                       "            return BACKDROP_COLOR;\n"
                       "        }\n"
                       "        else if (edge_distance>-outline_width)\n"
                       "        {\n"
                       "            return vec4(BACKDROP_COLOR.rgb, (outline_width+edge_distance)/blend_width);\n"
                       "        }\n"
                       "        else\n"
                       "        {\n"
                       "            return vec4(0.0, 0.0, 0.0, 0.0);\n"
                       "        }\n"
                       "    #else\n"
                       "        if (edge_distance>0.0)\n"
                       "        {\n"
                       "            return vertexColor;\n"
                       "        }\n"
                       "        else if (edge_distance>-blend_width)\n"
                       "        {\n"
                       "            return vec4(vertexColor.rgb, 1.0+edge_distance/blend_width);\n"
                       "        }\n"
                       "        else\n"
                       "        {\n"
                       "            return vec4(0.0, 0.0, 0.0, 0.0);\n"
                       "        }\n"
                       "    #endif\n"
                       "}\n"
                       "#endif\n"
                       "\n"
                       "\n"
                       "void main(void)\n"
                       "{\n"
                       "\n"
                       "#ifdef USE_SIGNED_DISTNACE_FIELD\n"
                       "\n"
                       "    float mml = osg_TextureQueryLOD(glyphTexture, texCoord).x;\n"
                       "\n"
                       "    float near_transition = 0.0;\n"
                       "    float far_transition = 1.0;\n"
                       "\n"
                       "    vec4 color;\n"
                       "    if (mml<near_transition) color = distanceFieldColor();\n"
                       "    else if (mml>far_transition) color = textureColor();\n"
                       "    else color = mix(distanceFieldColor(), textureColor(), (mml-near_transition)/(far_transition-near_transition));\n"
                       "\n"
                       "#else\n"
                       "\n"
                       "    vec4 color = textureColor();\n"
                       "\n"
                       "#endif\n"
                       "\n"
                       "    if (color.a==0.0) discard;\n"
                       "\n"
                       "    osg_FragColor = color;\n"
                       "}\n"
                       "\n";
