TOPDIR = ../..
include $(TOPDIR)/Make/makedefs

DIRS = \
	hangglide\
	osgbillboard\
	osgcluster\
	osgconv\
	osgcopy\
	osgcube\
	osgimpostor\
	osgreflect\
	osgscribe\
	osgstereoimage\
	osgtext\
	osgtexture\
	osgviews\
	osgversion\
	sgv


include $(TOPDIR)/Make/makedirrules
